Revert "Rollup commit of changes to support latest RCE prototype after November integration campaign"
This reverts commit 17e03b6bcd5668c948bc5d14cc6fa1fc2293b4fc.

On running quick-start, build was failing due to the following error message:

TpcMilliSliceDump_module.cc:140:83: error: no matching function for call to ‘lbne::TpcMicroSlice::nanoSlice(int&) const’
      std::unique_ptr<const TpcNanoSlice> nanoslice = microslice->nanoSlice(*i_nano);